name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  image_picker_for_web: ^2.1.12
  file_picker: ^8.0.6
  web: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
